#!/bin/bash

start() {
	/media/fat/Scripts/cardscan.py -d
	/media/fat/Scripts/gamewatch.py -d
}

stop() {
	killall cardscan.py
	killall gamewatch.py
}

case "$1" in
  start)
	start
        ;;
  stop) 
	stop
        ;;
  restart)
	stop
	start
	;;
#  reload)
#	reload
#	;;
  *)
#	 echo "Usage: $0 {start|stop|restart|reload}"
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
